#Requires -Version 5.1
<#
.SYNOPSIS
  One-shot setup for Bruker CT Algotom Toolkit (Windows + NVIDIA GPU).
.DESCRIPTION
  Installs Miniconda if needed, creates conda env "algotom-gpu",
  installs Algotom + Astra Toolbox, writes env\activate.ps1, runs smoke test.
#>
$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $Root

function Write-Step([string]$Message) {
    Write-Host ""
    Write-Host "==> $Message" -ForegroundColor Cyan
}

function Test-Command([string]$Name) {
    return [bool](Get-Command $Name -ErrorAction SilentlyContinue)
}

function Get-CondaExe {
    $candidates = @(
        "$env:USERPROFILE\miniconda3\Scripts\conda.exe",
        "$env:USERPROFILE\Miniconda3\Scripts\conda.exe",
        "$env:LOCALAPPDATA\miniconda3\Scripts\conda.exe",
        "$env:ProgramData\miniconda3\Scripts\conda.exe",
        "C:\ProgramData\miniconda3\Scripts\conda.exe"
    )
    foreach ($c in $candidates) {
        if (Test-Path $c) { return $c }
    }
    if (Test-Command "conda") {
        return (Get-Command conda).Source
    }
    return $null
}

Write-Host "Bruker CT Algotom Toolkit — setup" -ForegroundColor Green
Write-Host "Repo root: $Root"

# --- Prerequisites ---
Write-Step "Checking Git"
if (-not (Test-Command "git")) {
    throw "Git is not installed. Install from https://git-scm.com/download/win and re-run."
}
git --version

Write-Step "Checking NVIDIA GPU (nvidia-smi)"
if (-not (Test-Command "nvidia-smi")) {
    Write-Host "WARNING: nvidia-smi not found. GPU recon will fail until NVIDIA drivers are installed." -ForegroundColor Yellow
} else {
    nvidia-smi
}

# --- Miniconda ---
Write-Step "Locating / installing Miniconda"
$condaExe = Get-CondaExe
if (-not $condaExe) {
    $installer = Join-Path $Root ".miniconda_installer.exe"
    $url = "https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe"
    Write-Host "Downloading Miniconda..."
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    Invoke-WebRequest -Uri $url -OutFile $installer
    $prefix = Join-Path $env:USERPROFILE "miniconda3"
    Write-Host "Installing Miniconda to $prefix (silent)..."
    $args = @("/S", "/InstallationType=JustMe", "/AddToPath=0", "/RegisterPython=0", "/D=$prefix")
    $p = Start-Process -FilePath $installer -ArgumentList $args -Wait -PassThru
    if ($p.ExitCode -ne 0) {
        throw "Miniconda installer failed with exit code $($p.ExitCode)"
    }
    Remove-Item $installer -Force -ErrorAction SilentlyContinue
    $condaExe = Join-Path $prefix "Scripts\conda.exe"
    if (-not (Test-Path $condaExe)) {
        throw "Miniconda installed but conda.exe not found at $condaExe"
    }
}
Write-Host "Using conda: $condaExe"
& $condaExe --version

# Make sure conda can run from this shell
(& $condaExe "shell.powershell" "hook") | Out-String | Invoke-Expression

$EnvName = "algotom-gpu"
Write-Step "Creating / updating conda env '$EnvName' (Python 3.11)"
$envList = & $condaExe env list | Out-String
if ($envList -match "(?m)^\s*$EnvName\s") {
    Write-Host "Env already exists — updating packages..."
} else {
    & $condaExe create -y -n $EnvName python=3.11
}

Write-Step "Installing Algotom + deps from conda-forge"
& $condaExe install -y -n $EnvName -c conda-forge algotom matplotlib tqdm h5py pyyaml pillow tifffile

Write-Step "Installing Astra Toolbox (GPU)"
& $condaExe install -y -n $EnvName -c astra-toolbox -c nvidia astra-toolbox

Write-Step "Installing Gradio (GUI)"
& $condaExe run -n $EnvName python -m pip install --upgrade "gradio>=4.0"

# --- activate helper ---
Write-Step "Writing env\activate.ps1"
$envDir = Join-Path $Root "env"
New-Item -ItemType Directory -Force -Path $envDir | Out-Null
$activatePath = Join-Path $envDir "activate.ps1"
$activateContent = @"
# Auto-generated by setup.ps1 — activates the algotom-gpu conda env
`$condaExe = '$condaExe'
(& `$condaExe 'shell.powershell' 'hook') | Out-String | Invoke-Expression
conda activate $EnvName
Write-Host "Activated conda env: $EnvName" -ForegroundColor Green
"@
Set-Content -Path $activatePath -Value $activateContent -Encoding UTF8

# --- Smoke test ---
Write-Step "Running smoke test"
$pythonExe = & $condaExe run -n $EnvName python -c "import sys; print(sys.executable)"
Write-Host "Python: $pythonExe"
& $condaExe run -n $EnvName --no-capture-output python (Join-Path $Root "scripts\smoke_test.py")
if ($LASTEXITCODE -ne 0) {
    throw "Smoke test failed (exit $LASTEXITCODE)."
}

Write-Host ""
Write-Host "SETUP COMPLETE" -ForegroundColor Green
Write-Host "Next (no more commands needed):"
Write-Host "  Double-click  Start Toolkit.bat"
Write-Host "Then paste your Bruker scan folder path into the GUI and click Preview."
