#Requires -Version 5.1
<#
.SYNOPSIS
  One-shot setup for Bruker CT Algotom Toolkit (Windows + NVIDIA GPU).
.DESCRIPTION
  Installs Miniconda if needed, creates conda env "algotom-gpu",
  installs Algotom + Astra Toolbox, writes env\activate.ps1, runs smoke test.
#>
$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $Root

function Write-Step([string]$Message) {
    Write-Host ""
    Write-Host "==> $Message" -ForegroundColor Cyan
}

function Test-Command([string]$Name) {
    return [bool](Get-Command $Name -ErrorAction SilentlyContinue)
}

function Get-CondaExe {
    $candidates = @(
        "$env:USERPROFILE\miniconda3\Scripts\conda.exe",
        "$env:USERPROFILE\Miniconda3\Scripts\conda.exe",
        "$env:LOCALAPPDATA\miniconda3\Scripts\conda.exe",
        "$env:ProgramData\miniconda3\Scripts\conda.exe",
        "C:\ProgramData\miniconda3\Scripts\conda.exe"
    )
    foreach ($c in $candidates) {
        if (Test-Path $c) { return $c }
    }
    if (Test-Command "conda") {
        return (Get-Command conda).Source
    }
    return $null
}

function Invoke-CondaChecked([string[]]$CondaArgs) {
    Write-Host ("conda " + ($CondaArgs -join " "))
    & $script:condaExe @CondaArgs
    if ($LASTEXITCODE -ne 0) {
        throw "conda failed (exit $LASTEXITCODE): $($CondaArgs -join ' ')"
    }
}

Write-Host "Bruker CT Algotom Toolkit - setup" -ForegroundColor Green
Write-Host "Repo root: $Root"

# --- Prerequisites ---
Write-Step "Checking Git"
if (-not (Test-Command "git")) {
    throw "Git is not installed. Install from https://git-scm.com/download/win and re-run."
}
git --version

Write-Step "Checking NVIDIA GPU (nvidia-smi)"
if (-not (Test-Command "nvidia-smi")) {
    Write-Host "WARNING: nvidia-smi not found. GPU recon will fail until NVIDIA drivers are installed." -ForegroundColor Yellow
} else {
    nvidia-smi
}

# --- Miniconda ---
Write-Step "Locating / installing Miniconda"
$condaExe = Get-CondaExe
if (-not $condaExe) {
    $installer = Join-Path $Root ".miniconda_installer.exe"
    $url = "https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe"
    Write-Host "Downloading Miniconda..."
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    Invoke-WebRequest -Uri $url -OutFile $installer
    $prefix = Join-Path $env:USERPROFILE "miniconda3"
    Write-Host "Installing Miniconda to $prefix (silent)..."
    $argList = @("/S", "/InstallationType=JustMe", "/AddToPath=0", "/RegisterPython=0", "/D=$prefix")
    $p = Start-Process -FilePath $installer -ArgumentList $argList -Wait -PassThru
    if ($p.ExitCode -ne 0) {
        throw "Miniconda installer failed with exit code $($p.ExitCode)"
    }
    Remove-Item $installer -Force -ErrorAction SilentlyContinue
    $condaExe = Join-Path $prefix "Scripts\conda.exe"
    if (-not (Test-Path $condaExe)) {
        throw "Miniconda installed but conda.exe not found at $condaExe"
    }
}
$script:condaExe = $condaExe
Write-Host "Using conda: $condaExe"
& $condaExe --version

# Newer Miniconda requires accepting Anaconda channel Terms of Service
Write-Step "Accepting conda channel Terms of Service"
& $condaExe tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main
& $condaExe tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r
& $condaExe tos accept --override-channels --channel https://repo.anaconda.com/pkgs/msys2

# NOTE: do NOT run conda shell.powershell hook here.
# On some lab PCs PATH contains unquoted "Program Files" entries and the hook crashes.
# We always call conda.exe directly instead.

$CondaEnvName = "algotom-gpu"
Write-Step "Creating / updating conda env '$CondaEnvName' (Python 3.11)"
$envList = & $condaExe env list | Out-String
if ($envList -match [regex]::Escape($CondaEnvName)) {
    Write-Host "Env already exists - updating packages..."
} else {
    Invoke-CondaChecked @("create", "-y", "-n", $CondaEnvName, "-c", "conda-forge", "python=3.11")
}

Write-Step "Installing Algotom + deps from conda-forge"
Invoke-CondaChecked @(
    "install", "-y", "-n", $CondaEnvName, "-c", "conda-forge",
    "algotom", "matplotlib", "tqdm", "h5py", "pyyaml", "pillow", "tifffile"
)

Write-Step "Installing Astra Toolbox (GPU)"
Invoke-CondaChecked @(
    "install", "-y", "-n", $CondaEnvName,
    "-c", "astra-toolbox", "-c", "nvidia", "-c", "conda-forge",
    "astra-toolbox"
)

Write-Step "Installing Gradio (GUI)"
& $condaExe run -n $CondaEnvName python -m pip install --upgrade "gradio>=4.0"
if ($LASTEXITCODE -ne 0) {
    throw "Gradio install failed (exit $LASTEXITCODE)."
}

# --- activate helper ---
Write-Step "Writing env\activate.ps1"
$envDir = Join-Path $Root "env"
New-Item -ItemType Directory -Force -Path $envDir | Out-Null
$activatePath = Join-Path $envDir "activate.ps1"
$activateContent = @"
# Auto-generated by setup.ps1 - activates the algotom-gpu conda env via conda.exe
`$condaExe = '$condaExe'
Write-Host "Use: & `$condaExe run -n $CondaEnvName python ..." -ForegroundColor Green
Write-Host "Or double-click Start Toolkit.bat" -ForegroundColor Green
"@
Set-Content -Path $activatePath -Value $activateContent -Encoding ASCII

# --- Smoke test ---
Write-Step "Running smoke test"
$pythonExe = & $condaExe run -n $CondaEnvName python -c "import sys; print(sys.executable)"
Write-Host "Python: $pythonExe"
& $condaExe run -n $CondaEnvName --no-capture-output python (Join-Path $Root "scripts\smoke_test.py")
if ($LASTEXITCODE -ne 0) {
    throw "Smoke test failed (exit $LASTEXITCODE)."
}

Write-Host ""
Write-Host "SETUP COMPLETE" -ForegroundColor Green
Write-Host "Next (no more commands needed):"
Write-Host "  Double-click  Start Toolkit.bat"
Write-Host "Then paste your Bruker scan folder path into the GUI and click Preview."
